# Generated by Django 6.0.5 on 2026-05-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='store',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='stores',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sold_on',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_bought',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_sold',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
