# Generated by Django 6.0.5 on 2026-08-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_category_item_image_url_item_size_item_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
